name: PR Lint

on:
  pull_request:
    types: [ opened, edited, reopened, synchronize ]

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: morrisoncole/pr-lint-action@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          title-regex: "^[a-z0-9\\s]+$"
          on-failed-regex-fail-action: true
          on-failed-regex-create-review: false
          on-failed-regex-request-changes: false
          on-failed-regex-comment: "The PR Title is not valid. Please make sure to only use small case letters and numbers."
          on-succeeded-regex-dismiss-review-comment: "The PR Title is valid. Good job!"